title: Citra Space Docs
tagline: Space Object Identification at Scale
remote_theme: just-the-docs/just-the-docs
color_scheme: citra_dark
version: "0.2.1"

defaults:
  - scope:
      path: ""
    values:
      layout: default

callouts_level: quiet
callouts:
  note:
    color: green
  important:
    color: yellow
  warning:
    color: red